#!/usr/bin/perl

=head1 NAME

jp4sh - A JMX Shell

=cut

use Term::ReadLine;
use Term::ANSIColor;

# Menu
my $MENU = 
  [
     {
      command => "incoming",
      shortcut => "inc",
      submenu => [
                    { command => "show", exec => \&cmd_incoming_show, regexp => qr/^(\d+)$/ },
                    { command => "failed", exec => \&cmd_incoming_failed, },
                    { command => "activate", exec => \&cmd_incoming_activate, },
                    { command => "delete", exec => \&cmd_incoming_delete }
                 ],
     },
     { 
      label => "Message",
      command => "message",
      shortcut => "m",
      submenu => [
                    { command => "show", exec => \&cmd_message_show, regexp => qr/^(\d+)$/ },
                    { command => "activate", exec => \&cmd_message_activate }
                 ]
     },
     {
      label => "Incident",
      command =>  "incident",
      shortcut => "i",
      submenu => [
                    { command => "show", exec => \&cmd_incident_show, regexp => qr/^(\d+)$/ },
                 ]
     },
     {
      label => "Logging",
      command => "log" 
     },
     { 
      label => "Statistics",
      command =>  "stats" 
     },
  ];

my $GLOBAL_COMMANDS =
  [
     { 
      command => "cd",
      exec => \&cmd_cd,
      desc => "Change current operation level"
     },
     { 
      command => "ls",
      exec => \&cmd_ls,
      desc => "Show content of current level"
     },
     { 
      command => "set",
      exec => \&cmd_set,
      desc => "Set the value of an attribute"
     },
     {
      command => "get",
      exec => \&cmd_get,
      desc => "Get the value of an attribute"
     },
     { 
      command => "exec",
      exec => \&cmd_exec,
      desc  => "Execute an operation showing the result"
     },
     { 
      command => "info"
      exec => \&cmd_info,
      desc => "Show information of the connected server"
     },
     {        
      command => "quit",
      exec => sub { exit 0; },
      desc => "Quit this shell"
     },
     {        
      command => "server",
      exec => \&cmd_server,
      desc => "Change the server"
     },
     {        
      command => "quit",
      exec => sub { exit 0; } 
     }
  ];


